version: "3.8"
services:
  domoticz:
    image: domoticz/domoticz:stable
    container_name: domoticz
    restart: unless-stopped
    # Pass devices to container
    # devices:
    #   - "/dev/serial/by-id/usb-0658_0200-if00-port0:/dev/ttyACM0"
    ports:
      - 8764:8080
      - 6144:6144
      - 1443:1443
    volumes:
      - ./config:/opt/domoticz/userdata
    environment:
      - TZ=Europe/Amsterdam
      #- LOG_PATH=/opt/domoticz/userdata/domoticz.log
      #- PUID=1000
      #- PGID=1000
      #- WEBROOT=domoticz #optional
      #- "DBASE=<path to database>" #optional
    restart: unless-stopped
    #  nextcloud:
#    build: nextcloud_dockerfile
#    container_name: nextcloud
#    env_file: .env
#    environment:
#        - APACHE_DISABLE_REWRITE_IP=1
#        - TRUSTED_PROXIES=swag
#        - OVERWRITEHOST=nextcloud.<SUBDOMAIN>.duckdns.org
#        - OVERWITEPROTOCOL=https
#        - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.<SUBDOMAIN>.duckdns.org
#        - NEXTCLOUD_DATA_DIR=/var/www/html/data
#        - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/NEXTCLOUD_ADMIN_USER
#        - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/NEXTCLOUD_ADMIN_PASSWORD
#        - POSTGRES_HOST=postgres
#        - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_NC_PASSWORD
#        - POSTGRES_DB_FILE=/run/secrets/POSTGRES_NC_DB
#        - POSTGRES_USER_FILE=/run/secrets/POSTGRES_NC_USER
#    volumes:
#        - ./nextcloud/html:/var/www/html
#        - ./nextcloud/config:/var/www/html/config
#        - /media/DATA:/data
#    restart: always
#    depends_on:
#      - pihole
#      - postgres
#    networks:
#      - backend
#    secrets:
#      - NEXTCLOUD_ADMIN_USER
#      - NEXTCLOUD_ADMIN_PASSWORD
#      - POSTGRES_NC_PASSWORD
#      - POSTGRES_NC_DB
#      - POSTGRES_NC_USER
#      - MY_DDNS_DOMAIN

secrets:
  EMAIL:
    file: ./secrets/EMAIL
  NEXTCLOUD_ADMIN_USER:
    file: ./secrets/NEXTCLOUD_ADMIN_USER
  NEXTCLOUD_ADMIN_PASSWORD:
    file: ./secrets/NEXTCLOUD_ADMIN_PASSWORD

networks:
    frontend:
    backend:
      external: false
    docker_proxy:
      external: false
