version: "3.8"
services:
#  nextcloud:
#    build: nextcloud_dockerfile
#    container_name: nextcloud
#    env_file: .env
#    environment:
#        - APACHE_DISABLE_REWRITE_IP=1
#        - TRUSTED_PROXIES=swag
#        - OVERWRITEHOST=nextcloud.<SUBDOMAIN>.duckdns.org
#        - OVERWITEPROTOCOL=https
#        - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.<SUBDOMAIN>.duckdns.org
#        - NEXTCLOUD_DATA_DIR=/var/www/html/data
#        - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/NEXTCLOUD_ADMIN_USER
#        - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/NEXTCLOUD_ADMIN_PASSWORD
#        - POSTGRES_HOST=postgres
#        - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_NC_PASSWORD
#        - POSTGRES_DB_FILE=/run/secrets/POSTGRES_NC_DB
#        - POSTGRES_USER_FILE=/run/secrets/POSTGRES_NC_USER
#    volumes:
#        - ./nextcloud/html:/var/www/html
#        - ./nextcloud/config:/var/www/html/config
#        - /media/DATA:/data
#    restart: always
#    depends_on:
#      - pihole
#      - postgres
#    networks:
#      - backend
#    secrets:
#      - NEXTCLOUD_ADMIN_USER
#      - NEXTCLOUD_ADMIN_PASSWORD
#      - POSTGRES_NC_PASSWORD
#      - POSTGRES_NC_DB
#      - POSTGRES_NC_USER
#      - MY_DDNS_DOMAIN

secrets:
  EMAIL:
    file: ./secrets/EMAIL
  NEXTCLOUD_ADMIN_USER:
    file: ./secrets/NEXTCLOUD_ADMIN_USER
  NEXTCLOUD_ADMIN_PASSWORD:
    file: ./secrets/NEXTCLOUD_ADMIN_PASSWORD

networks:
    frontend:
    backend:
      external: false
    docker_proxy:
      external: false
